stages:
  - build
  - docker

variables:
  IMAGE_NAME: "mon-image-de-contener"
  IMAGE_TAG: "latest"
  DOCKER_REGISTRY: "registry.gitlab.com"

# Étape de build Gradle
build:
  stage: build
  script:
    - ./gradlew clean build

# Étape de création de l'image Docker
docker:
  stage: docker
  script:
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main  # ou ta branche principale (par exemple `master`)
