# Utilise une image de base avec OpenJDK 17
FROM openjdk:17-jdk-slim

# Définir un répertoire de travail pour l'application
WORKDIR /app

# Copier l'artefact JAR dans l'image Docker (ajuste si nécessaire)
COPY build/libs/*.jar app.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour exécuter l'application Java
ENTRYPOINT ["java", "-jar", "app.jar"]
